missionNamespace setVariable ["FU_vehicleQueue", [], true];
missionNamespace setVariable ["FU_onlinePilots", [], true];
missionNamespace setVariable ["FU_isTraining", false, true];
missionNamespace setVariable ["FU_missionStarted", false, true];
missionNamespace setVariable ["FU_missionStarted_IDAP", false, true];
missionNamespace setVariable ["FU_completedTasks", 0, true];
missionNamespace setVariable ["FU_completedMissions", 0, true];
missionNamespace setVariable ["FU_trainingCooldown", 0, true];
missionNamespace setVariable ["FU_trainingPeople", 0, true];
missionNamespace setVariable ["FU_trainingLocations", allMapMarkers select {"FU_TrainingLocation_" in _x}, true];
missionNamespace setVariable ["FU_trainingLocationsLZ", allMapMarkers select {"FU_TrainingLZ_" in _x}, true];

//Roles
missionNamespace setVariable ["FU_roles", [
	["Autorifleman", [[["LMG_03_F","","","optic_Hamr",["200Rnd_556x45_Box_Tracer_Red_F",200],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",17],[],""],["FU_Uni_bison",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_CableTie",2],["ACE_epinephrine",4],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellBlue",1,1]]],["FU_Vest_rig_blackb",[["HandGrenade",2,1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,17],["200Rnd_556x45_Box_Tracer_Red_F",2,200]]],["B_AssaultPack_blk",[["ACE_EntrenchingTool",1],["200Rnd_556x45_Box_Tracer_Red_F",2,200]]],"FU_helm_bison","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch","ACE_NVG_Wide_Black"]],[]]],
	["Crewman (Artillery)", [[["arifle_SPAR_01_blk_F","","","optic_Hamr",["30Rnd_556x45_Stanag_Tracer_Red",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",17],[],""],["FU_Uni_bison",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_CableTie",2],["ACE_epinephrine",4],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellBlue",1,1]]],["FU_Vest_rig_black",[["ACE_artilleryTable",1],["ACE_RangeTable_82mm",1],["HandGrenade",2,1],["SmokeShell",2,1],["30Rnd_556x45_Stanag_Tracer_Red",10,30],["16Rnd_9x21_Mag",2,17]]],["B_AssaultPack_blk",[["ACE_EntrenchingTool",1],["ToolKit",1],["MineDetector",1]]],"H_Tank_eaf_F","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch","ACE_NVG_Wide_Black"]],[]]],
	["Crewman (Mechanized/Armored)", [[["arifle_SPAR_01_blk_F","","","optic_Hamr",["30Rnd_556x45_Stanag_Tracer_Red",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",17],[],""],["FU_Uni_bison",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_CableTie",2],["ACE_epinephrine",4],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellBlue",1,1]]],["FU_Vest_rig_black",[["HandGrenade",2,1],["SmokeShell",2,1],["30Rnd_556x45_Stanag_Tracer_Red",10,30],["16Rnd_9x21_Mag",2,17]]],["B_AssaultPack_blk",[["ACE_EntrenchingTool",1],["ToolKit",1],["MineDetector",1]]],"H_Tank_eaf_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch","ACE_NVG_Wide_Black"]],[]]],
	["Engineer", [[["arifle_SPAR_01_blk_F","","","optic_Hamr",["30Rnd_556x45_Stanag_Tracer_Red",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",17],[],""],["FU_Uni_bison",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_CableTie",2],["ACE_epinephrine",4],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellBlue",1,1]]],["FU_Vest_rig_blackb",[["ACE_M26_Clacker",1],["HandGrenade",2,1],["SmokeShell",2,1],["30Rnd_556x45_Stanag_Tracer_Red",9,30],["16Rnd_9x21_Mag",2,17]]],["FU_kitbag_black",[["ACE_EntrenchingTool",1],["ToolKit",1],["MineDetector",1],["DemoCharge_Remote_Mag",3,1]]],"FU_helm_bison","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch","ACE_NVG_Wide_Black"]],[]]],
	["Marksman", [[["FU_Rifle_p_b","","","optic_DMS",["20Rnd_762x51_Mag",20],[],"bipod_01_F_blk"],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",17],[],""],["FU_Uni_bison",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_CableTie",2],["ACE_epinephrine",4],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellBlue",1,1]]],["FU_Vest_rig_blackb",[["HandGrenade",2,1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,17],["20Rnd_762x51_Mag",7,20]]],["B_AssaultPack_blk",[["ACE_EntrenchingTool",1],["20Rnd_762x51_Mag",8,20]]],"FU_helm_bison","",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch","ACE_NVG_Wide_Black"]],[]]],
	["Medic", [[["arifle_SPAR_01_blk_F","","","optic_Hamr",["30Rnd_556x45_Stanag_Tracer_Red",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",17],[],""],["FU_Uni_bison",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_CableTie",2],["ACE_epinephrine",4],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellBlue",1,1]]],["FU_Vest_rig_blackb",[["HandGrenade",1,1],["SmokeShell",5,1],["30Rnd_556x45_Stanag_Tracer_Red",10,30],["16Rnd_9x21_Mag",2,17]]],["FU_kitbag_black",[["ACE_EntrenchingTool",1],["ACE_elasticBandage",70],["ACE_bloodIV",5],["ACE_bloodIV_500",10],["ACE_epinephrine",30],["ACE_morphine",15],["ACE_splint",20],["ACE_tourniquet",10]]],"FU_helm_bison","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch","ACE_NVG_Wide_Black"]],[]]],
	["Pilot (Helicopter)", [[["arifle_SPAR_01_blk_F","","","optic_Hamr",["30Rnd_556x45_Stanag_Tracer_Red",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",17],[],""],["FU_Uni_bison",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_CableTie",2],["ACE_epinephrine",4],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellBlue",1,1]]],["FU_Vest_rig_black",[["HandGrenade",2,1],["SmokeShell",2,1],["30Rnd_556x45_Stanag_Tracer_Red",10,30],["16Rnd_9x21_Mag",2,17]]],["B_AssaultPack_blk",[["ACE_EntrenchingTool",1],["ToolKit",1]]],"FU_NVG_helm","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch",""]],[]]],
	["Pilot (Plane)", [[["SMG_03C_TR_black","","","optic_Aco_smg",["50Rnd_570x28_SMG_03",50],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",17],[],""],["U_I_pilotCoveralls",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_CableTie",2],["ACE_epinephrine",4],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellBlue",1,1],["50Rnd_570x28_SMG_03",1,50]]],[],["B_Kitbag_sgg",[["ToolKit",1]]],"H_PilotHelmetFighter_I","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch",""]],[]]],
	["Rifleman", [[["arifle_SPAR_02_blk_F","","","optic_Hamr",["30Rnd_556x45_Stanag_Tracer_Red",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",17],[],""],["FU_Uni_bison",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_CableTie",2],["ACE_epinephrine",4],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellBlue",1,1]]],["FU_Vest_rig_blackb",[["HandGrenade",2,1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,17],["30Rnd_556x45_Stanag_Tracer_Red",11,30]]],["B_AssaultPack_blk",[["ACE_EntrenchingTool",1]]],"FU_helm_bison","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch","ACE_NVG_Wide_Black"]],[]]],
	["Rifleman (AT)", [[["arifle_SPAR_01_blk_F","","","optic_Hamr",["30Rnd_556x45_Stanag_Tracer_Red",30],[],""],["launch_NLAW_F","","","",[],[],""],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",17],[],""],["FU_Uni_bison",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_CableTie",2],["ACE_epinephrine",4],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellBlue",1,1]]],["FU_Vest_rig_blackb",[["HandGrenade",2,1],["SmokeShell",2,1],["30Rnd_556x45_Stanag_Tracer_Red",10,30],["16Rnd_9x21_Mag",2,17]]],["B_AssaultPack_blk",[["ACE_EntrenchingTool",1]]],"FU_helm_bison","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch","ACE_NVG_Wide_Black"]],[]]],
	["Team Leader", [[["arifle_SPAR_01_GL_blk_F","","","optic_Hamr",["30Rnd_556x45_Stanag_Tracer_Red",30],["1Rnd_HE_Grenade_shell",1],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",17],[],""],["FU_Uni_bison",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_CableTie",2],["ACE_epinephrine",4],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellBlue",1,1]]],["FU_Vest_rig_blackb",[["HandGrenade",2,1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,17],["30Rnd_556x45_Stanag_Tracer_Red",10,30]]],["B_RadioBag_01_black_F",[["ACE_EntrenchingTool",1],["1Rnd_HE_Grenade_shell",15,1]]],"FU_helm_bison","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc148jem","ItemCompass","ItemWatch","ACE_NVG_Wide_Black"]],[]]],
	["UAV Operator", [[["arifle_SPAR_01_blk_F","","","optic_Hamr",["30Rnd_556x45_Stanag_Tracer_Red",30],[],""],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",17],[],""],["FU_Uni_bison",[["ACE_elasticBandage",10],["ACE_packingBandage",5],["ACE_CableTie",2],["ACE_epinephrine",4],["ACE_morphine",2],["ACE_splint",2],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["SmokeShellBlue",1,1]]],["FU_Vest_rig_blackb",[["HandGrenade",2,1],["SmokeShell",2,1],["30Rnd_556x45_Stanag_Tracer_Red",10,30],["16Rnd_9x21_Mag",2,17]]],["I_UAV_01_backpack_F",[]],"FU_helm_bison","",["Binocular","","","",[],[],""],["ItemMap","I_UavTerminal","TFAR_anprc148jem","ItemCompass","ItemWatch","ACE_NVG_Wide_Black"]],[]]]
], true];

addMissionEventHandler ["EntityKilled", {
	params ["_unit", "_killer", "_instigator", "_useEffects"];
	
	if(isPlayer _instigator) then {
		_currentKills = _instigator getVariable "FU_totalKills";
		_instigator setVariable ["FU_totalKills", _currentKills + 1, true];
	};
}];

//Handle disconnects
_pilotDisconnected = addMissionEventHandler ["HandleDisconnect", {
	params ["_unit", "_id", "_uid", "_name"];
	
	private _onlinePilots = missionNamespace getVariable "FU_onlinePilots";
	_onlinePilots = _onlinePilots - [_name];
	missionNamespace setVariable ["FU_onlinePilots", _onlinePilots, true];

	private _vehicleQueue = missionNamespace getVariable "FU_vehicleQueue";
	_vehicleQueue = _vehicleQueue - [_name];
	missionNamespace setVariable ["FU_vehicleQueue", _vehicleQueue, true];

	false;
}];